version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Bind-mount backend code for live updates  

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
     - ./frontend:/usr/share/nginx/html  # Bind-mount frontend files
